#!/usr/bin/env python3
"""Rebuild the News timeline of the Traffic group from data/news.json.

Each news item has a year, a month and a text; links in the text are written
as [label](url). Items are shown newest first, grouped by year and month
(items of the same month keep their order in the file). Everything between
the NEWS markers in news.html is regenerated; the rest of the page is left
untouched. The home page shows the latest items in its Highlights rotator,
reading them from news.html. Edit the data by hand or with the editor
(admin/people/, "News" tab).

Standard library only.
"""
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'news.json')
PAGE = os.path.join(ROOT, 'news.html')
START = '<!-- NEWS:START -->'
END = '<!-- NEWS:END -->'
MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']
LINK = re.compile(r'\[([^\]]+)\]\(([^)\s]+)\)')


def render_text(text):
    out, last = [], 0
    for m in LINK.finditer(text):
        out.append(html.escape(text[last:m.start()], quote=False))
        label, url = html.escape(m.group(1), quote=False), html.escape(m.group(2), quote=True)
        external = ' target="_blank" rel="noopener"' if re.match(r'https?://', m.group(2)) else ''
        out.append(f'<a href="{url}"{external}>{label}</a>')
        last = m.end()
    out.append(html.escape(text[last:], quote=False))
    return ''.join(out)


def sort_key(item):
    month = item.get('month', '')
    return (-int(item['year']), -(MONTHS.index(month) if month in MONTHS else -1))


def render(news):
    news = sorted(news, key=sort_key)   # stable: same-month items keep their order
    years = []
    for item in news:
        if not years or years[-1][0] != item['year']:
            years.append((item['year'], []))
        months = years[-1][1]
        if not months or months[-1][0] != item.get('month', ''):
            months.append((item.get('month', ''), []))
        months[-1][1].append(item)

    lines = ['<!-- Generated by scripts/build_news.py from data/news.json: '
             'edit the data (or use admin/people/), not this block. -->']
    for year, months in years:
        lines += [f'<section class="news-year" aria-labelledby="y{year}">',
                  f'  <h2 class="news-year-title" id="y{year}">{year}</h2>',
                  '  <ol class="news-list">']
        for month, items in months:
            lines += ['    <li class="news-entry">',
                      f'      <p class="news-month">{html.escape(month)}</p>',
                      '      <ul class="news-items">']
            lines += [f'        <li>{render_text(i["text"])}</li>' for i in items]
            lines += ['      </ul>', '    </li>']
        lines += ['  </ol>', '</section>']
    return '\n'.join('        ' + line for line in lines)


def build():
    with open(DATA, encoding='utf-8') as f:
        news = json.load(f)['news']
    with open(PAGE, encoding='utf-8') as f:
        page = f.read()
    if START not in page or END not in page:
        sys.exit(f'news.html: markers {START} / {END} not found')
    block = f'{START}\n{render(news)}\n        {END}'
    page = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda _: block, page, flags=re.S)
    with open(PAGE, 'w', encoding='utf-8') as f:
        f.write(page)


if __name__ == '__main__':
    build()
    print('news.html rebuilt from data/news.json')
