#!/usr/bin/env python3
"""Rebuild the Collaborations page of the Traffic group from data/collaborations.json.

The data holds the "current" and the "past" collaborations, each with the
name of the contact person, its type ("company" or "academic"), a link, the
organization, the shared topic and an optional logo. In each group the
companies are listed first.
Everything between the COLLABORATIONS markers in collaborations.html is
regenerated; the rest of the page is left untouched. Edit the data by hand
or with the editor (admin/people/, "Collaborations" tab).

Standard library only.
"""
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'collaborations.json')
PAGE = os.path.join(ROOT, 'collaborations.html')
START = '<!-- COLLABORATIONS:START -->'
END = '<!-- COLLABORATIONS:END -->'


def esc(text):
    return html.escape(text or '', quote=True)


def card(item):
    name = esc(item['name'])
    link = item.get('link')
    if link:
        external = re.match(r'https?://', link)
        target = ' target="_blank" rel="noopener"' if external else ''
        name = f'<a href="{esc(link)}"{target}>{name}{" ↗" if external else ""}</a>'
    company = item.get('type') == 'company'
    lines = [f'<li class="collab{" collab--company" if company else ""}">']
    if item.get('logo') or company:
        lines.append('  <div class="collab-head">')
        if company:
            lines.append('    <span class="collab-kind">Industry</span>')
        if item.get('logo'):
            alt = esc(item.get('organization') or item['name'])
            lines.append(f'    <img class="collab-logo" src="{esc(item["logo"])}" alt="{alt}" loading="lazy">')
        lines.append('  </div>')
    lines.append(f'  <h3 class="collab-name">{name}</h3>')
    if item.get('organization'):
        lines.append(f'  <p class="collab-org">{esc(item["organization"])}</p>')
    if item.get('topic'):
        lines.append(f'  <p class="collab-topic">{esc(item["topic"])}</p>')
    lines.append('</li>')
    return lines


def section(title, intro, items, alt):
    lines = [f'<section class="section page-body{" section-alt" if alt else ""}">',
             '  <div class="container">',
             '    <div class="section-head">',
             f'      <h2 class="section-title">{title}</h2>']
    if intro:
        lines.append(f'      <p class="section-intro">{intro}</p>')
    lines += ['    </div>', '    <ul class="collab-grid">']
    # Companies first, otherwise the order of the data file.
    for item in sorted(items, key=lambda i: i.get('type') != 'company'):
        lines += ['      ' + line for line in card(item)]
    lines += ['    </ul>', '  </div>', '</section>']
    return lines


def render(data):
    lines = ['<!-- Generated by scripts/build_collaborations.py from data/collaborations.json: '
             'edit the data (or use admin/people/), not this block. -->']
    if data.get('current'):
        lines += section('Current collaborations', 'Research groups we are working with, and the topics we share.',
                         data['current'], alt=False)
    if data.get('past'):
        lines += section('Past collaborations', '', data['past'], alt=bool(data.get('current')))
    return '\n'.join('    ' + line for line in lines)


def build():
    with open(DATA, encoding='utf-8') as f:
        data = json.load(f)
    with open(PAGE, encoding='utf-8') as f:
        page = f.read()
    if START not in page or END not in page:
        sys.exit(f'collaborations.html: markers {START} / {END} not found')
    block = f'{START}\n{render(data)}\n    {END}'
    page = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda _: block, page, flags=re.S)
    with open(PAGE, 'w', encoding='utf-8') as f:
        f.write(page)


if __name__ == '__main__':
    build()
    print('collaborations.html rebuilt from data/collaborations.json')
