#!/usr/bin/env python3
"""Build the Workshops & Special Issues page of the Traffic site from data/workshops.json.

The page shows, as cards and in two separate sections, the workshops organized
by the group and the special issues edited by its members (newest first).
Header, menu and footer are taken from collaborations.html, so the page has
the site layout.

Standard library only.
"""
import html
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'workshops.json')
TEMPLATE = os.path.join(ROOT, 'collaborations.html')
PAGE = os.path.join(ROOT, 'workshops.html')
GROUP = 'University of Napoli Federico II'
TITLE = 'Workshops & Special Issues'


def esc(text):
    return html.escape(str(text or ''), quote=True)


def ext(url):
    return ' target="_blank" rel="noopener"' if re.match(r'https?://', url or '') else ''


def people(label, items):
    """Group members first and highlighted; the others in plain chips."""
    chips = []
    for p in sorted(items, key=lambda p: p.get('affiliation') != GROUP):
        ours = p.get('affiliation') == GROUP
        role = f' <small>({esc(p["role"])})</small>' if p.get('role') else ''
        title = f' title="{esc(p["affiliation"])}"' if p.get('affiliation') else ''
        chips.append(f'<li class="{"is-ours" if ours else ""}"{title}>{esc(p["name"])}{role}</li>')
    return (f'<p class="event-label">{esc(label)}</p>\n'
            f'              <ul class="event-people">{"".join(chips)}</ul>')


def workshop_card(w):
    return f'''          <article class="event-card">
            <header class="event-card-head">
              <span class="event-badge">{esc(w['year'])}</span>
              <p class="event-venue">{esc(w['conference'])}</p>
            </header>
            <div class="event-card-body">
              <h3 class="event-title"><a href="{esc(w['link'])}"{ext(w['link'])}>{esc(w['acronym'])}</a></h3>
              <p class="event-subtitle">{esc(w['title'])}</p>
              <p class="event-meta"><span>{esc(w['dates'])}</span><span>{esc(w['place'])}</span></p>
              {people('Chairs', w['chairs'])}
              <a href="{esc(w['link'])}" class="card-link"{ext(w['link'])}>Workshop website →</a>
            </div>
          </article>'''


def special_issue_card(s):
    links = ''.join(f'<a href="{esc(l["url"])}" class="card-link"{ext(l["url"])}>{esc(l["label"])}{" ↗" if ext(l["url"]) else " →"}</a>'
                    for l in s.get('links', []))
    return f'''          <article class="event-card event-card--issue">
            <header class="event-card-head">
              <span class="event-badge">{esc(s['year'])}</span>
              <p class="event-venue">{esc(s['journal'])}</p>
            </header>
            <div class="event-card-body">
              <p class="card-kicker">{esc(s['kind'])}</p>
              <h3 class="event-title event-title--long">{esc(s['title'])}</h3>
              {people('Guest editors', s['editors'])}
              <div class="event-links">{links}</div>
            </div>
          </article>'''


def render(data):
    workshops = sorted(data.get('workshops', []), key=lambda w: -int(w['year']))
    issues = sorted(data.get('special_issues', []), key=lambda s: -int(s['year']))
    return f'''
    <!-- Generated by scripts/build_workshops.py from data/workshops.json: edit the data, not this page. -->
    <section class="page-hero">
      <div class="container">
        <nav class="breadcrumb" aria-label="Breadcrumb"><a href="index.html">Home</a> <span class="crumb-sep" aria-hidden="true">/</span> <span>{esc(TITLE)}</span></nav>
        <h1 class="page-title">{esc(TITLE)}</h1>
        <p class="page-lead">{esc(data.get('intro'))}</p>
        <nav class="page-jump" aria-label="On this page"><a href="#workshops">Workshops <span>{len(workshops)}</span></a><a href="#special-issues">Special issues <span>{len(issues)}</span></a></nav>
      </div>
    </section>

    <section class="section page-body" id="workshops" aria-labelledby="workshops-title">
      <div class="container">
        <div class="section-head">
          <h2 id="workshops-title" class="section-title">Workshops</h2>
          <p class="section-intro">International workshops organized by members of the group, held with major conferences.</p>
        </div>
        <div class="event-grid">
{chr(10).join(workshop_card(w) for w in workshops)}
        </div>
      </div>
    </section>

    <section class="section page-body section-alt" id="special-issues" aria-labelledby="si-title">
      <div class="container">
        <div class="section-head">
          <h2 id="si-title" class="section-title">Special issues</h2>
          <p class="section-intro">Special issues and special sections of international journals guest-edited by members of the group.</p>
        </div>
        <div class="event-grid">
{chr(10).join(special_issue_card(s) for s in issues)}
        </div>
      </div>
    </section>
'''


def build():
    with open(DATA, encoding='utf-8') as f:
        data = json.load(f)
    with open(TEMPLATE, encoding='utf-8') as f:
        page = f.read()
    head, rest = page.split('<main id="main">', 1)
    _, tail = rest.split('</main>', 1)
    page = head + '<main id="main">' + render(data) + '\n  </main>' + tail
    page = re.sub(r'<title>.*?</title>', f'<title>{esc(TITLE)} | Traffic</title>', page, count=1, flags=re.S)
    page = re.sub(r'<meta name="description" content="[^"]*">',
                  '<meta name="description" content="Workshops organized and special issues edited by the Traffic research group.">', page, count=1)
    page = page.replace(' aria-current="page"', '')
    page = page.replace('class="nav-link">Workshops &amp; Special Issues</a>',
                        'class="nav-link" aria-current="page">Workshops &amp; Special Issues</a>')
    with open(PAGE, 'w', encoding='utf-8') as f:
        f.write(page)


if __name__ == '__main__':
    build()
    print('workshops.html rebuilt from data/workshops.json')
