#!/usr/bin/env python3
"""Rebuild the People page of the Traffic group from data/people.json.

The JSON holds the head of the group ("principal"), the current "members"
and the former members ("alumni"), each with name, role, photo, affiliation,
phone, emails, homepage and Google Scholar URL. Everything between the
PEOPLE markers in people.html is regenerated; the rest of the page is left
untouched. Edit the data by hand or with scripts/people_admin.py.

Standard library only.
"""
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'people.json')
PAGE = os.path.join(ROOT, 'people.html')
START = '<!-- PEOPLE:START -->'
END = '<!-- PEOPLE:END -->'
ADDRESS = 'DIETI, Via Claudio 21 — 80125 Napoli, Italy · Fax +39 081 768-3816'


def esc(value):
    return html.escape(value or '', quote=True)


def indent(block, spaces):
    pad = ' ' * spaces
    return '\n'.join(pad + line if line else line for line in block.split('\n'))


def meta(person):
    rows = []
    if person.get('affiliation'):
        rows.append(f'<li>{esc(person["affiliation"])}</li>')
    if person.get('phone'):
        rows.append(f'<li><span class="k">Tel</span> {esc(person["phone"])}</li>')
    for email in person.get('emails') or []:
        # Spelled out with [at] to keep the address away from simple harvesters.
        rows.append(f'<li><span class="k">Email</span> {esc(email.replace("@", "[at]"))}</li>')
    if not rows:
        return ''
    return '<ul class="person-meta">\n' + '\n'.join('  ' + r for r in rows) + '\n</ul>\n'


def links(person):
    # Empty hrefs are hidden by the stylesheet; the card opens the first filled link.
    return ('<div class="person-links">\n'
            f'  <a class="person-link" href="{esc(person.get("homepage"))}">Homepage</a>\n'
            f'  <a class="person-link person-link--scholar" href="{esc(person.get("scholar"))}">Google Scholar</a>\n'
            '</div>')


def card(person, tag='li', variant='', with_meta=True):
    classes = 'person' + (f' person--{variant}' if variant else '')
    body = (f'<h3 class="person-name">{esc(person["name"])}</h3>\n'
            + (f'<p class="person-role">{esc(person["role"])}</p>\n' if person.get('role') else '')
            + (meta(person) if with_meta else '')
            + links(person))
    photo = person.get('photo') or 'images/pictures/placeholder.svg'
    return (f'<{tag} class="{classes}">\n'
            f'  <img src="{esc(photo)}" alt="" class="person-photo" loading="lazy">\n'
            '  <div class="person-body">\n'
            f'{indent(body, 4)}\n'
            '  </div>\n'
            f'</{tag}>')


def section(css_class, title_id, title, content, intro=''):
    intro_html = f'\n      <p class="section-intro">{esc(intro)}</p>' if intro else ''
    return (f'<section class="section page-body {css_class}" aria-labelledby="{title_id}">\n'
            '  <div class="container">\n'
            '    <div class="section-head">\n'
            f'      <h2 id="{title_id}" class="section-title">{title}</h2>{intro_html}\n'
            '    </div>\n'
            f'{indent(content, 4)}\n'
            '  </div>\n'
            '</section>')


def render(data):
    parts = []
    if data.get('principal'):
        parts.append(section('section-lead', 'head-title', 'Head of the group',
                             card(data['principal'], 'article', 'principal'), ADDRESS))
    if data.get('members'):
        cards = '\n'.join(indent(card(p), 2) for p in data['members'])
        parts.append(section('section-members', 'members-title', 'Members',
                             f'<ul class="people-grid">\n{cards}\n</ul>'))
    if data.get('alumni'):
        cards = '\n'.join(indent(card(p, variant='alumnus', with_meta=False), 2) for p in data['alumni'])
        parts.append(section('section-alt', 'alumni-title', 'Former members',
                             f'<ul class="people-grid people-grid--alumni">\n{cards}\n</ul>'))
    note = ('<!-- Generated by scripts/build_people.py from data/people.json: '
            'edit the data (or run scripts/people_admin.py), not this block. -->')
    return indent('\n\n'.join([note] + parts), 4)


def build():
    with open(DATA, encoding='utf-8') as f:
        data = json.load(f)
    with open(PAGE, encoding='utf-8') as f:
        page = f.read()
    if START not in page or END not in page:
        sys.exit(f'people.html: markers {START} / {END} not found')
    block = f'{START}\n{render(data)}\n    {END}'
    page = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda _: block, page, flags=re.S)
    with open(PAGE, 'w', encoding='utf-8') as f:
        f.write(page)


if __name__ == '__main__':
    build()
    print('people.html rebuilt from data/people.json')
