#!/usr/bin/env python3
"""Rebuild the research topics of the Traffic group from data/topics.json.

The data lists the research areas; each area has topics, and each topic an
optional link and optional tools (name + link). Two places are generated:

  index.html      the "Research topics & tools" section, between the TOPICS markers
  every page      the "Topics" menu of the header, between the TOPICS-MENU markers
                  (links are adjusted to the depth of each page)

Edit the data by hand or with the editor (admin/people/, "Topics" tab).

Standard library only.
"""
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'topics.json')
HOME = os.path.join(ROOT, 'index.html')
START, END = '<!-- TOPICS:START -->', '<!-- TOPICS:END -->'
MENU_START, MENU_END = '<!-- TOPICS-MENU:START -->', '<!-- TOPICS-MENU:END -->'
SKIP_DIRS = {'.git', '.github', 'admin', 'data', 'scripts', 'node_modules'}


def esc(text):
    return html.escape(text or '', quote=True)


def external(url):
    return bool(re.match(r'https?://', url or ''))


def href(url, prefix):
    """Links in the data are relative to the site root; adjust them for a page `prefix` deep."""
    if not url or external(url) or url.startswith(('/', '#', 'mailto:')):
        return url
    return prefix + url


def attrs(url, prefix=''):
    extra = ' target="_blank" rel="noopener"' if external(url) else ''
    return f'href="{esc(href(url, prefix))}"{extra}'


def topic_target(topic):
    """Where a topic leads: its own page, else its only tool, else the topics section."""
    if topic.get('link'):
        return topic['link']
    tools = [t for t in topic.get('tools') or [] if t.get('link')]
    return tools[0]['link'] if len(tools) == 1 else ''


# --------------------------------------------------------------------------
# Home section
# --------------------------------------------------------------------------

def render_home(data):
    lines = ['<!-- Generated by scripts/build_topics.py from data/topics.json: '
             'edit the data (or use admin/people/), not this block. -->',
             '<div class="section-head">',
             '  <h2 id="topics-title" class="section-title">Research topics &amp; tools</h2>']
    if data.get('intro'):
        lines.append(f'  <p class="section-intro">{esc(data["intro"])}</p>')
    lines += ['</div>', '', '<div class="areas">']
    for number, area in enumerate(data.get('areas') or [], 1):
        lines += ['  <article class="area">',
                  f'    <header class="area-head"><span class="area-num">{number:02d}</span><h3>{esc(area["title"])}</h3></header>',
                  '    <ul class="area-topics">']
        for topic in area.get('topics') or []:
            name = esc(topic['name'])
            head = (f'<a {attrs(topic["link"])} class="area-topic">{name}</a>' if topic.get('link')
                    else f'<span class="area-topic">{name}</span>')
            chips = ''.join(f'<a {attrs(t["link"])}>{esc(t["name"])}{" ↗" if external(t["link"]) else ""}</a>'
                            if t.get('link') else f'<span>{esc(t["name"])}</span>'
                            for t in topic.get('tools') or [])
            lines.append(f'      <li>{head}' + (f'<div class="chips">{chips}</div>' if chips else '') + '</li>')
        lines += ['    </ul>', '  </article>']
    lines.append('</div>')
    return '\n'.join('        ' + line if line else '' for line in lines)


# --------------------------------------------------------------------------
# Header menu
# --------------------------------------------------------------------------

def render_menu(data, prefix, on_home):
    section = '#topics' if on_home else f'{prefix}index.html#topics'
    areas = data.get('areas') or []
    lines = []
    for index, area in enumerate(areas):
        lines += ['<div class="mega-col">', f'  <p class="mega-heading">{esc(area["title"])}</p>']
        for topic in area.get('topics') or []:
            target = topic_target(topic)
            link = attrs(target, prefix) if target else f'href="{section}"'
            tools = ' · '.join(esc(t['name']) for t in topic.get('tools') or [])
            small = f' <small>{tools}</small>' if tools else ''
            lines.append(f'  <a {link}>{esc(topic["name"])}{small}</a>')
        if index == len(areas) - 1:
            lines.append(f'  <a href="{prefix}other.html">Other activities</a>')
        lines.append('</div>')
    return '\n'.join(' ' * 16 + line for line in lines)


def page_prefix(path):
    depth = os.path.relpath(path, ROOT).count(os.sep)
    return '../' * depth


def html_pages():
    for folder, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in files:
            if name.endswith('.html'):
                yield os.path.join(folder, name)


def replace_block(text, start, end, block, indent):
    return re.sub(re.escape(start) + r'.*?' + re.escape(end),
                  lambda _: f'{start}\n{block}\n{indent}{end}', text, flags=re.S)


def build():
    with open(DATA, encoding='utf-8') as f:
        data = json.load(f)
    menus = 0
    for path in html_pages():
        with open(path, 'rb') as f:
            raw = f.read()
        # Only pages with the TRAFFIC header are touched (some legacy pages are not UTF-8).
        if MENU_START.encode() not in raw and os.path.abspath(path) != HOME:
            continue
        page = raw.decode('utf-8')
        updated = page
        if MENU_START in page:
            on_home = os.path.abspath(path) == HOME
            updated = replace_block(updated, MENU_START, MENU_END, render_menu(data, page_prefix(path), on_home), ' ' * 16)
            menus += 1
        if os.path.abspath(path) == HOME:
            if START not in updated:
                sys.exit(f'index.html: markers {START} / {END} not found')
            updated = replace_block(updated, START, END, render_home(data), ' ' * 8)
        if updated != page:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(updated)
    return menus


if __name__ == '__main__':
    count = build()
    print(f'Research topics rebuilt: home section and the menu of {count} pages')
