#!/usr/bin/env python3
"""Build the Community page of the Traffic site from data/community.json.

The page lists, in two separate sections, the workshops organized by the group
and the special issues edited by its members (newest first). Header, menu and
footer are taken from collaborations.html, so the page has the site layout.

Standard library only.
"""
import html
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'community.json')
TEMPLATE = os.path.join(ROOT, 'collaborations.html')
PAGE = os.path.join(ROOT, 'community.html')
GROUP = 'University of Napoli Federico II'


def esc(text):
    return html.escape(str(text or ''), quote=True)


def ext(url):
    return ' target="_blank" rel="noopener"' if re.match(r'https?://', url or '') else ''


def people(items):
    """Group members first and highlighted; the others with their affiliation."""
    chips = []
    for p in sorted(items, key=lambda p: p.get('affiliation') != GROUP):
        ours = p.get('affiliation') == GROUP
        role = f' <small>({esc(p["role"])})</small>' if p.get('role') else ''
        title = f' title="{esc(p["affiliation"])}"' if p.get('affiliation') else ''
        chips.append(f'<li class="{"is-ours" if ours else ""}"{title}>{esc(p["name"])}{role}</li>')
    return '<ul class="event-people">' + ''.join(chips) + '</ul>'


def workshop(w):
    return f'''          <li class="event">
            <div class="event-year">{esc(w['year'])}</div>
            <div class="event-body">
              <p class="card-kicker">{esc(w['conference'])} · {esc(w['dates'])} · {esc(w['place'])}</p>
              <h3 class="event-title"><a href="{esc(w['link'])}"{ext(w['link'])}>{esc(w['acronym'])}</a></h3>
              <p class="event-subtitle">{esc(w['title'])}</p>
              <p class="event-label">Chairs</p>
              {people(w['chairs'])}
              <a href="{esc(w['link'])}" class="card-link"{ext(w['link'])}>Workshop website →</a>
            </div>
          </li>'''


def special_issue(s):
    links = ''.join(f'<a href="{esc(l["url"])}" class="card-link"{ext(l["url"])}>{esc(l["label"])}{" ↗" if ext(l["url"]) else " →"}</a>'
                    for l in s.get('links', []))
    return f'''          <li class="event">
            <div class="event-year">{esc(s['year'])}</div>
            <div class="event-body">
              <p class="card-kicker">{esc(s['kind'])} · {esc(s['journal'])}</p>
              <h3 class="event-title">{esc(s['title'])}</h3>
              <p class="event-label">Guest editors</p>
              {people(s['editors'])}
              <div class="event-links">{links}</div>
            </div>
          </li>'''


def render(data):
    workshops = sorted(data.get('workshops', []), key=lambda w: -int(w['year']))
    issues = sorted(data.get('special_issues', []), key=lambda s: -int(s['year']))
    return f'''
    <!-- Generated by scripts/build_community.py from data/community.json: edit the data, not this page. -->
    <section class="page-hero">
      <div class="container">
        <nav class="breadcrumb" aria-label="Breadcrumb"><a href="index.html">Home</a> <span class="crumb-sep" aria-hidden="true">/</span> <span>Community</span></nav>
        <h1 class="page-title">Community</h1>
        <p class="page-lead">{esc(data.get('intro'))}</p>
        <nav class="page-jump" aria-label="On this page"><a href="#workshops">Workshops <span>{len(workshops)}</span></a><a href="#special-issues">Special issues <span>{len(issues)}</span></a></nav>
      </div>
    </section>

    <section class="section page-body" id="workshops" aria-labelledby="workshops-title">
      <div class="container">
        <div class="section-head">
          <h2 id="workshops-title" class="section-title">Workshops</h2>
          <p class="section-intro">International workshops organized by members of the group, held with major conferences.</p>
        </div>
        <ol class="event-list">
{chr(10).join(workshop(w) for w in workshops)}
        </ol>
      </div>
    </section>

    <section class="section page-body section-alt" id="special-issues" aria-labelledby="si-title">
      <div class="container">
        <div class="section-head">
          <h2 id="si-title" class="section-title">Special issues</h2>
          <p class="section-intro">Special issues and special sections of international journals guest-edited by members of the group.</p>
        </div>
        <ol class="event-list">
{chr(10).join(special_issue(s) for s in issues)}
        </ol>
      </div>
    </section>
'''


def build():
    with open(DATA, encoding='utf-8') as f:
        data = json.load(f)
    with open(TEMPLATE, encoding='utf-8') as f:
        page = f.read()
    head, rest = page.split('<main id="main">', 1)
    _, tail = rest.split('</main>', 1)
    page = head + '<main id="main">' + render(data) + '\n  </main>' + tail
    page = re.sub(r'<title>.*?</title>', '<title>Community | Traffic</title>', page, count=1, flags=re.S)
    page = re.sub(r'<meta name="description" content="[^"]*">',
                  '<meta name="description" content="Workshops organized and special issues edited by the Traffic research group.">', page, count=1)
    page = page.replace(' aria-current="page"', '')
    page = page.replace('class="nav-link">Community</a>', 'class="nav-link" aria-current="page">Community</a>')
    with open(PAGE, 'w', encoding='utf-8') as f:
        f.write(page)


if __name__ == '__main__':
    build()
    print('community.html rebuilt from data/community.json')
